### ISSUE TITLE
Autofill Firefox for Android

### ISSUE THREAD

**Issue by 011B31** [PhilippC/keepass2android#1399]
Hello there,
due to the big firefox Update, the autofill function unfortunately doesn't Work anymore. Are there any workarounds or prospects dir this issue? Thanks.

**Comment by PhilippC** [comment]
for me it's still working, even though the Autofill popup disappears sometimes and I need to put the cursor into the entry field a few times until it stays there. This seems to be a Firefox quirk, IMO. Which Firefox version are you referring to? mine is 80.1.2 on Android 10.

**Comment by Murgeye** [comment]
Seems to be very unreliable for me in 80.1.2 on Android 10. Sometimes I can use it as normal, but other times I cannot even trigger the auto fill popup at all. If it shows up, sometimes choosing an entry does nothing but close the popup.

**Comment by 011B31** [comment]
I'm also using 80.1.2, but on android 9. In Chrome it works fine (unfortunately). Seems to be the same on my device like on Murgeye's. 
I think it's a FF issue too but that doesn't necessarily mean that it is going to be solved from Mozilla..

**Comment by bluezed** [comment]
I have Android 10 and Firefox 80.1.3 and have the same problem. Most of the time the pop up appears and disappears immediately so I cannot use it. Often it doesn't appear at all.
Also the long press feature where you could select Autofill as an option is no longer there.

I've also created a bug in the Firefox Fenix repo:
https://github.com/mozilla-mobile/fenix/issues/14633

I'm actually using Fennec F-Droid for the time being because of this issue ☹️

**Comment by 011B31** [comment]
In the nightly version of FF, the problem seems to be solved!

**Comment by IronJunkie** [comment]
> In the nightly version of FF, the problem seems to be solved!

Is this still working for you? I am getting the same behaviour on all FF apps (release, beta & nightly). It seems to be website dependant, from my very limited testing on 3 sites, eg github works every time, others don't despite reentering password/user fields and/or refreshing page 10's of times.

Workaround seems to be to change focus to another app & then back to FF & KP2A fill popup appears in user name/password field.

Can others please confirm. Tanx

**Comment by sophiekuehn** [comment]
Doesn't opens up at all for me after the FF upgrade. Using Android 8 Oreo.

**Comment by azlux** [comment]
See the issue in video : ttps://cloud.azlux.fr/s/TEafw8JZT2KsrEk

**Comment by qcksilver** [comment]
I'm having the same problem in the new Firefox for android, and it's also not consistent across websites. I noticed that on some websites where I have this problem if my keyboard doesn't appear after clicking in a password field (which is rare) the keypass2andriod dialog does not disappear. Also the rare time there is a delay in my keyboard appearing the kepass dialog does not disappear until my keyboard appears. I never had this problem with the old version of Firefox.

Maybe the new version of Firefox changed how it loads the keyboard? (I'm not a developer so I'm probably wrong, but hopefully this helps someone smart diagnose the problem).

**Comment by MuadDibIII** [comment]
How is life funny.
I just logged in here using the autofill pop-up. But the reason I logged in was to say that it doesn't work for me most of the times after the big Firefox update...

**Comment by strassan** [comment]
For me, it doesn't work at all anymore - neither for Github, nor any other site I tried so far. The Autofill bar just doesn't show up.

I'm using Firefox 81.1.2 on Android 8.0.0, but the issue started in an earlier version of Firefox (right after the large update)

**Comment by MuadDibIII** [comment]
I actually notice that it works well if the database is open. Not closed, not closed with quick unlock option. It has to be really open

**Comment by Murgeye** [comment]
> I actually notice that it works well if the database is open. Not closed, not closed with quick unlock option. It has to be really open

Does not seem to make a difference for me. What sometimes helps is opening and closing the FireFox dot menu or opening the app switch screen, but it's not reliable for me.

**Comment by matthias-matze** [comment]
Hy, 

Samedi issue here (android 10, samsung a70 stock, latest firefox stable and beta)

Juste notice that when i change the keyboard, the autofill plugin appears,  and disappears when the news keyboard displays.

**Comment by flatline-studios** [comment]
I've noticed that it works fine if the input box has focus, but the keyboard is not showing, which incidentally is the case on Github.

Any other site where you are required to tap and give focus to the text fields, very briefly brings up the autofill popup, but as soon as the keyboard opens, it seems to register as a dismissal of the popup.

Its like when the keyboard opens, it triggers an event that acts as though you're trying to close the popup by tapping elsewhere on the screen.

A proposed workaround would be to enable a close button, and remove the "tap elsewhere closes the popup", until this issue is resolved by Firefox.

**Comment by Apfelgelee** [comment]
Hello everybody,
unfortunately the workaround of "flatline-studios" doesn't work for me :-(

>     1. Have focus on the username field.
>     2. Tap the three dots to bring up the menu.
>     3. Tap back on the username field.
>     4. You'll notice that the keyboard is not showing, the username field has focus, and the keepass2android popup will be shown.

I have tried all possible settings and input variants in both Firefox for Android and Keepass2Android. Nothing has usefully solved the problem with entering a username and password. The input field disappears immediately after switching from Keepass2Android to Firefox.

The only annoying stopgap solution I've found is this:
1) Open the website in Firefox ==> the login window appears.
2) Select "Fill out with Keepass2Android" ==> Switch to Keepass2Android.
3) Select the password entry in Keepass2Android ==> Switch to Firefox, the input window has disappeared.
4) Close Firefox using the Android Task Manager.
5) Start Firefox and go to website again ==> login window appears.
6) Now, in addition to "Fill in with Keepass2Andorid", there is the option that directly bears the name of the password entry. ==> Selecting this option.
7) Username and password from Keepass2Android are taken over directly without changing the app, the input field is still available ==> tap "OK" and be happy ;-)

I once made a request in the Mozilla support forum: https://support.mozilla.org/de/questions/1309038 Let's see what happens.

regards
Michael

**Comment by kkulczak** [comment]
I'd like that right now, switching from firefox stable to firefox nightly solved this problem for me.

**Comment by sophiekuehn** [comment]
> I'd like to report that right now, switching from firefox stable to firefox nightly solved this problem for me.

Sadly that's not the case here using Android 8.

**Comment by IronJunkie** [comment]
> I'd like to report that right now, switching from firefox stable to firefox nightly solved this problem for me.

Still not working for me, eg on google.com, nightlies used to be built from different code base from one night to another, I think, not sure if this is still true, so possibly you have one that works or it's the intermittent issue as it sometimes works on some sites (I'm on Android 10 stock, no FF addons on nightly, but seeing exactly the same behaviour on FF release with addons & Beta , but does work on FF Focus)

**Comment by TonyGravagno** [comment]
I'm using Firefox Beta, v83. I've had this auto fill issue for a couple years - and yes, I've donated beers and birthday donations. ;)
After all this time I decided to come here and check the status of this issue. Specifically, it's hit or miss as to whether KP2A will find an entry for a web page or do an autofill. But then I just had the same experience, that a login to Github works perfectly, finds the entry, populates the user/psw fields. I'm sorry I can't provide better diagnostic info but I do want to confirm this anomaly. HTH TYVM

**Comment by Dimas-sc** [comment]
Same issue with Firefox 84 😥

**Comment by uhausbrand** [comment]
Same issue. Basically none of the workarounds are helping. Even if the autofill option shows and i select an entry, it won't enter it. Instead it returns to no popup shown again.

**Comment by philipreimer** [comment]
With Firefox 84.1.2 on Android 10 (Nokia 8.1) Autofill from Keepass2Android does not work at all anymore.

The first issue is that the Autofill popup dialog does not appear automatically anymore or only briefly appears and then instantly disappears again. Most of the times you can get the Autofill popup dialog to appear by alternatively tapping into the login and password fields 5 - 10 times.

But even if you get the Autofill popup dialog to appear, no login data gets filled into the login form.

**Comment by cjk28** [comment]
Looks like they have made a workaround in this keepass client: https://github.com/Kunzisoft/KeePassDX/issues/725

**Comment by Offerel** [comment]
I have the same issue with Firefox stable and also nightly. It doesn't matter if plugins are installed.

**Comment by PhilippC** [comment]
@cjk28 thanks for the hint. I had to change a few more things and I think it's greatly improved now, even though Firefox still seems a little bit buggy in some cases. This fix will be included in 1.08d-r1 (should be available soon through https://play.google.com/apps/testing/keepass2android.keepass2android)

**Comment by Murgeye** [comment]
Just updated to 1.08d-r1. Sadly, it seems AutoFill in Firefox got even more wonky for me. Some pages (e.g. Github) seem to work perfectly now, while on others (e.g. twitter) I need several tries to get the dialog to show up and then it disappears again after selecting an entry without the possibility to fill any fields. So pretty much the same behavior @philipreimer  reported.
I've noticed that sometimes the dialog will popup just barely on screen, making it impossible to interact with - I will try to catch a screenshot the next time this happens.

FireFox Version: 84.1.3

**Comment by PhilippC** [comment]
@Murgeye which Android version are you on?

**Comment by cjk28** [comment]
Generally improved, cheers! Github and twitter seem ok for me on android 10.

vanguardinvestor.co.uk seems a bit problematic, effectively the 2nd issue that philipreimer mentioned. in Chrome if I click in the username field i get the keepass diaglog instantly with "vanguardinvestor.co.uk", "Fill with Keepass2Android", and "Disable AutoFill for vanguardinvestor.co.uk"  - expected behaviour.
In firefox, after a few goes, I got the 2nd and 3rd of those, suggesting keepass hasn't found a match, after a few seconds the keepass dialog disappears. If I click the 2nd one, keepass immediately opens and shows the correct entry, but if I click the entry it does not get autofilled. I can sometimes get all 3 options to appear and then all is good, however the behaviour is really inconsistent.

**Comment by 011B31** [comment]
Just noticed that even though the database is locked, I'm able to fill in passwords. The dialogue pops up and suggests the login data with title. E.g. "amazon.de" or like in the screenshot "osiander".
![Screenshot_20210108-124258](https://user-images.githubusercontent.com/70767214/104011886-21047900-51af-11eb-94be-39443bf1dd6e.png)
![Screenshot_20210108-124306](https://user-images.githubusercontent.com/70767214/104011889-2235a600-51af-11eb-8dc5-670c69fba2aa.png)

**Comment by sophiekuehn** [comment]
No luck with 1.08d-r1 on Android 8.0. FF is current nightly.

**Comment by Murgeye** [comment]
> 
> 
> @Murgeye which Android version are you on?

I'm on Android 10.

**Comment by Murgeye** [comment]
Just noticed the same. This seems like a serious security issue to me :persevere: I can even fill in the password without quick unlocking

**Comment by Offerel** [comment]
I can't confirm filling in password with closed/unlocked db. Sure, if db is closed, I have the autofill option but when I click it, I must unlock the db first. Tested in latest Firefox with latest kp2a beta.

**Comment by Murgeye** [comment]
Agreed. There already is a new issue for this: [#1527](https://github.com/PhilippC/keepass2android/issues/1527)

**Comment by PhilippC** [comment]
thanks for the feedback. I found further workaround for some bad Firefox behavior and it seems to work quite nicely now (including the fix to the security bug - sorry for that). While testing, there were still a few cases where the prompt would not show up.
In these cases I could either bring it up by changing focus from username field to password or vice versa. If this didn't help, I could close Firefox (swipe out from recent tasks) and re-open it, then the prompt did show up. As I'm not experiencing this in Firefox Klar, I suppose it is an issue with Firefox/Firefox Nightly.

**Comment by PhilippC** [comment]
the fixes are included in 1.08d-r2 (https://play.google.com/apps/testing/keepass2android.keepass2android)

**Comment by PhilippC** [comment]
@Offerel @Murgeye @sophiekuehn I hope it is now working!?

**Comment by Offerel** [comment]
For me Autofill working now reliable in Firefox. I'm just still pretty frustrated with Firefox mobile. But that has nothing to do with KP2A. Currently there are so many bugs in Firefox mobile that it's really no fun to use this browser anymore. I have preferred Firefox for many years, and the change to the new structure has certainly done the browser a lot of good. Nevertheless, there are still a lot of open bugs, which are also reported and accepted. It just feels like nothing is fixed. No wonder that users are switching to alternative browsers in droves.

**Comment by sophiekuehn** [comment]
> @Offerel @Murgeye @sophiekuehn I hope it is now working!?

Sorry but no. Also with 1.08d-r2 i don't get a auto fill popup on Android 8.0. Maybe FF is using stuff that was introduced with 8.1 auto fill framework enhancements? https://developer.android.com/about/versions/oreo/android-8.1

**Comment by roedel1** [comment]
I can currently confirm and reproduce the Autofill behaviour.
_parallel post as in the corresponding Fenix Bug: [https://github.com/mozilla-mobile/fenix/issues/14633](url)_

Device: Sony Xperia XZ2 Compact
OS: Android 10 (Stock) 52.1.A.3.49
Mozilla Firefox: 84.1.4 (Firefox Daylight Channel from Google Play)
KeePass2Android: 1.08d-r2

- Popup-Behaviour is inconsistent but has definitely gotten better with KP2A-Upgrade to 1.08d-r1 and is now working nearly any time with 1.08d-r2. 
- I'm not able to reliably reproduce the behaviour depending on specific sites or forms. 
- Switching focus between input fields or apps currently brings up a clickable popup after 1-3 focus switches

I'll be happy to share device log data if it's helpful in tackling the issue.

Thank you for being here and working on the issue!
Stephan

**Comment by Murgeye** [comment]
I can confirm that it seems to work a bit better than before on Android 10. However, some websites still seem to be broken for me (e.g. twitter).

An improvement is that now the selected entry remains between two Autofill attempts, whereas before I had to reselect an entry multiple times.

Thanks for working on this, and if I can help debug in any way just ask.

**Comment by Taknok** [comment]
It is a global issue of the new firefox with password manager integration: [Issue 14633](https://github.com/mozilla-mobile/fenix/issues/14633#issuecomment-757528113)

**Comment by PhilippC** [comment]
> 
> 
> > @Offerel @Murgeye @sophiekuehn I hope it is now working!?
> 
> Sorry but no. Also with 1.08d-r2 i don't get a auto fill popup on Android 8.0. Maybe FF is using stuff that was introduced with 8.1 auto fill framework enhancements? https://developer.android.com/about/versions/oreo/android-8.1

It seems like this is really a Firefox restriction (or does it work with any other password manager?)

**Comment by PhilippC** [comment]
> Thanks for working on this, and if I can help debug in any way just ask.

@Murgeye Can you please double-check that you are on 1.08d-r2 (or later, I might release r3 soon but without changes to Autofill). If you are, can you enable debug logging in the app settings and send me a log after trying to use Autofill with twitter? (Please also note my comment above: 
> While testing, there were still a few cases where the prompt would not show up.
In these cases I could either bring it up by changing focus from username field to password or vice versa. If this didn't help, I could close Firefox (swipe out from recent tasks) and re-open it, then the prompt did show up. As I'm not experiencing this in Firefox Klar, I suppose it is an issue with Firefox/Firefox Nightly.

**Comment by ptar** [comment]
Thank you for working on thi issue!
I just installed KP2A 1.08d-r2 and it's definitely better than 1.08c: I could easily autofill the login credentials for github.
But I have another login site, for which I have stored multiple credentials. If I select one of the entries in the lower part of the list, KP2A Autofill always selects the first entry, which is wrong in the first place. But since the first entry refers to a ftp:-Url, it's even worse, because it doesn't even fit the url of the http:-site I've currently opened.
Thank you for checking this and fixing it!

**Comment by Murgeye** [comment]
> 
> 
> > Thanks for working on this, and if I can help debug in any way just ask.
> 
> @Murgeye Can you please double-check that you are on 1.08d-r2 (or later, I might release r3 soon but without changes to Autofill). If you are, can you enable debug logging in the app settings and send me a log after trying to use Autofill with twitter? (Please also note my comment above:
> 
> > While testing, there were still a few cases where the prompt would not show up.
> > In these cases I could either bring it up by changing focus from username field to password or vice versa. If this didn't help, I could close Firefox (swipe out from recent tasks) and re-open it, then the prompt did show up. As I'm not experiencing this in Firefox Klar, I suppose it is an issue with Firefox/Firefox Nightly.

This definitely happens in 1.08d-r2. Most times, changing the focus works, but other times it doesn't, or it clears an already selected entry. Closing the Firefox seems like a tedious workaround to be honest. I have attached the log and a video of how it works with twitter right now (this is one of the better cases, but I couldn't trigger the worst case right now).

https://user-images.githubusercontent.com/16648242/104446215-6acbd580-559a-11eb-93a4-b2f021011185.mp4
[Keepass2Android log.txt](https://github.com/PhilippC/keepass2android/files/5808282/Keepass2Android.log.txt)

**Comment by Murgeye** [comment]
Interesting: To record this I changed the mail entry and removed an additional string "email" in the entry. If I re-add the additional string, the behavior is much worse, causing the entry to get cleared multiple times. Here is the log for that, hope it helps.
[Keepass2Android log.txt](https://github.com/PhilippC/keepass2android/files/5808348/Keepass2Android.log.txt)

**Comment by PhilippC** [comment]
thanks @Murgeye for the log. It seems like Firefox is never disconnecting/cancelling in some cases from autofill service. I have therefore introduced a timeout for the lock (which avoids the flickering) for 1.08d-r3 which I'm currently uploading to beta channel. I also fixed the bug with selecting one of multiple search results.

**Comment by flowercow** [comment]
1.08d-r3 works with ff nightly, but when there are more entris, after choosing the right entry,  sometimes k2a still use the first one.
when work with ff 84, this issue still occur. and the  menu with three dot does not pop up

**Comment by PhilippC** [comment]
can anybody else confirm the issue with multiple entries still existing in 1.08d-r3? I cannot reproduce it anymore. @flowercow maybe you can send me a debug log after reproducing? (crocoapps@gmail.com)

**Comment by ptar** [comment]
With FF 84, I can't reproduce the issue with multiple entries (thanks for fixing). Note: The selected value is still not autofilled.

With FF 84, I can circumvent the problem with the not-appearing dialog by opening the 3-dot-menu and then tapping back on the entry field (let's call it "3-dotting"). On some pages, it works immediately that way, on others (like amazon) I had to try for a few times. After selecting an entry in K2A, getting back to the page and "3-dotting" the dialog, using the additional menu entry for the specific page does the job.

With FF nightly (210115), the "3-dotting" is not necessary anymore. 
The dialog appears immediately, I can select one out of many entries in K2A. After coming back, I see a K2A menu only with just one entry mentioning the page. The chosen credentials are filled into the fields after selecting this entry. (Tested with github, amazon, own provider's login)

For me, the behavior with FF nightly is sufficient, nevertheless I would prefer a direct autofill after the selection in K2A.

**Comment by Murgeye** [comment]
I can confirm that it works way better in 1.08d-r3, especially in Firefox nightly. I also cannot reproduce the multiple entry issue. I can, however, confirm that Autofill requires a second confirmation when selecting another entry.

**Comment by PhilippC** [comment]
in the previous implementation, I returned a "dataset" from my activity where the user selects an entry which is automatically filled on return in many apps/browsers, but some browsers including Firefox did not work with this at all. I am now returning a "response" containing that "dataset" - this is why you have to click the dataset once again, but at least it works. I'm not very happy with this either, but I think it's the best solution for now.

**Comment by qcksilver** [comment]
I recently switched over to the beta version specifically because of this issue. Currently on Version 1.09a-pre1 and switching to the beta channel did help a lot, but unfortunately not all the time. I would (roughly) estimate autofill in Firefox works about 80% of the time now. Actually had trouble logging into github just now, had to refresh the page a few times before the autofill dialog would stay visable instead of just appearing for a millisecond and then disappear.

I'm on Firefox for Android stable version 86.1.1 (Build #2015794883)

Thanks for all the work you've put in trying to fix this btw!

**Comment by ptar** [comment]
I'm wondering this bug is closed: It still exists in FF 87.0.0-rc.1, while it's gone in FF nightly for weeks now. Any idea?

**Comment by sophie-kuehn** [comment]
It also still exists for Android 8.0.
