### ISSUE TITLE
[QUESTION] Which option should I change to resolve the message about secure display?

### ISSUE THREAD

**Issue by iriman** [PhilippC/keepass2android#2418]
**What version of Keepass2Android are you using?**
1.09e-r7

**Android version:**
12

When I open Keepass2Android app I see this message:

> The currently valid display is not marked as secure. This means that screenshots might be taken by other apps. Keepass2Android is configured to display sensitive information on secure displays only. Please change to a secure display (e.g. by detaching an HDMI monitor) or change the app settings.

![Screenshot_20230915-103145_Keepass2Android](https://github.com/PhilippC/keepass2android/assets/8467903/dc9393a4-402e-40cb-865f-63fe2bfab6a1)

Which option should I change in the settings to resolve this security concern?

**Comment by iriman** [comment]
I noticed that whenever I play a video using VLC it is in casting mode by default:
![vlc](https://github.com/PhilippC/keepass2android/assets/8467903/e550bf87-fa5a-4265-b248-a19d9048d477)
So probably the problem is with Android.
For now I restarted my phone and VLC issue with opening videos in casting mode is solved. But since I hit the "disable this message" button on Keepass2Android I couldn't ckeck the issue with this app. I guess it is solved with Kp2A too, if I clear data and check again.

**Comment by hyproman** [comment]
At this point you've probably already cleared app data but for future reference:

There does not appear to be a way to reset the "disable this message" option from the app, so yes, unfortunately you would need to clear app data to re-enable checking for a secure display.

**Comment by linkp** [comment]
This is message still an issue. I just encountered it for the first time after connecting to another screen (streaming via Chromecast). It is even worse now, as the top line is covered by a black bar that says Keepass2Android, making that part of the text illegible. Thankfully, I was able to reboot as suggested in this issue, but it would be nice if we could safely work past this message somehow.

**Comment by PhilippC** [comment]
you can find this in future versions in settings - app - display.
