### ISSUE TITLE
:status header not found with nginx and http2

### ISSUE THREAD

**Issue by msrv** [PhilippC/keepass2android#44]
I've experienced a bug with the latest KeePass2Android and nginx/nextcloud 12.

When switching nginx to "http2" protocol, keepass2android is not able to access webdav locations any more on my server (Nextcloud 12).

Error is "expected :status header not found" in the app, the nginx error log shows status code 401 with the okhttp module.

When i switch nginx back to "normal" http and omit the http2 directive, everything works as expected.

Any ideas how to fix this?

Thank you!

**Comment by sfunk1x** [comment]
Also experiencing this issue.

**Comment by serenitatis** [comment]
Same here.

**Comment by Orochimarufan** [comment]
This seems to be caused by square/okhttp#640
Kind of puzzling, since that should have been fixed in 2014, before it was even included in KP2A. Well whatever, updating the dependencies should fix this, see also:
https://stackoverflow.com/questions/46807237/protocolexception-expected-status-header-not-present

**Comment by doctaweeks** [comment]
Are you running the nginx 1.13.6? A recent change is causing problems in older versions of okhttp: https://trac.nginx.org/nginx/ticket/1397

I don't believe the issue @Orochimarufan referenced is the issue in play. (That fix is included in okhttp 3.4.1).

Updating to the okhttp 3.5.0 or newer and it will work with the latest nginx.

**Comment by Orochimarufan** [comment]
@doctaweeks Thanks for clearing that up, I must have missed that nginx ticket.

Anyway, I guess we'll have to wait for a release including an updated okhttp version.

**Comment by PhilippC** [comment]
please switch to the beta channel to check if this is fixed with the next release. I have upgraded okhttp3.

**Comment by LouisMT** [comment]
I'm a beta tester on Google Play but I'm still having this issue. I got version 1.02, is this right? Or should it be 1.03?

**Comment by PhilippC** [comment]
It's 1.03 which is not yet released.

**Comment by blubbsy** [comment]
i'm also in the beta channel, but i'm not receiving version 1.03. When will be the updated version be available?
